# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &defaults
  adapter: postgresql
  host: ''
  min_messages: WARNING

development:
  <<: *defaults
  database: avi-lib_development

test:
  <<: *defaults
  database: avi-lib_test

production:
  <<: *defaults
  database: avi-lib_production

staging:
  <<: *defaults
  database: avi-lib_staging